# syntax=docker/dockerfile:1

FROM rust:1.68.0-slim-bullseye AS build

RUN apt update
RUN apt install -y libpq-dev

COPY global-ws /garthen/global-ws
COPY libs /garthen/libs
WORKDIR /garthen/global-ws

RUN cargo build --release
RUN mkdir /bin/garthen
RUN mv ./target/release/garthen-global-ws /bin/garthen

FROM debian:bullseye-slim

RUN apt update
RUN apt install -y libpq-dev

COPY --from=build /bin/garthen /bin/garthen

ENTRYPOINT ["/bin/garthen/garthen-global-ws"]
