# syntax=docker/dockerfile:1

FROM node:18.14.1-alpine AS build

COPY web-client /garthen/web-client
COPY libs /garthen/libs
WORKDIR /garthen/web-client

RUN npm install
RUN npm run build
RUN mkdir /bin/garthen; mkdir /bin/garthen/garthen-web-client
RUN mv ./.output/* /bin/garthen/garthen-web-client

FROM node:18.14.1-alpine

COPY --from=build /bin/garthen /bin/garthen

ENTRYPOINT ["node", "/bin/garthen/garthen-web-client/server/index.mjs"]
